# This workflow will publish jars to GitHub Packages.
# Currently, it must be triggered manually and uses Java 11
# (because there is no requirement for jpackage).

name: Publish to GitHub Packages

on: [workflow_dispatch]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt-hotspot'
      - name: Publish package
        run: ./gradlew publish -P toolchain=11
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}